### ISSUE TITLE
any chanche to support scss (sass) ?

### ISSUE THREAD

**Issue by quasiperfect** [weepower/wee#4]
great work i really love wee

**Comment by leigeber** [comment]
It has been suggested before but our plans for Wee 4 are to actually move from Less to PostCSS (https://trello.com/b/7KbnQra9/wee) in an effort to speed up the build process even more and keep our mixin syntax simple. I don't see us adding and maintaining SCSS as a result. Sorry to disappoint.

**Comment by quasiperfect** [comment]
thanks for your time PostCSS sounds good
